### ISSUE TITLE
Getting Claims from the Token

### ISSUE THREAD

**Issue by benhatton-unsw-edu-au** [stevenphaedonos/react-msal-jwt#4]
Hey Steven,
We're interested in reading claims, specifically "role" from the token - any thoughts on best way to do this?  The role claim should be populated automatically when users are assigned to a specific role in the AAD application record.
Cheers
Ben
b.hatton@unsw.edu.au

**Comment by stevenphaedonos** [comment]
Hi Ben,
After getting the access token back from Azure, you can simply call the appropriate Microsoft Graph endpoint with the token in the Auth header to get the user's roles. The relevant part of the MSAL docs [is here](https://github.com/tanzencoder/microsoft-authentication-library-for-js#4-use-the-token-as-a-bearer-in-an-http-request-to-call-the-microsoft-graph-or-a-web-api).

**Comment by benhatton-unsw-edu-au** [comment]
Hi Steven,

Thanks, we ended up adding the openid scope to the list of delegated permissions, and the role comes through in the ID token which is posted to the serverside code.

Cheers
Ben
